version: 2.1

default:
  environment: &envvars
    CONTAINER_NAME: quay.io/redsift/sandbox-python
    CIRCLE_REVERSE_DEPENDENCIES: sandbox-scipy sandbox-nltk sandbox-python-oninbox-ml
executors:
  dockexec:
    shell: /bin/bash
    environment: *envvars
    docker:
      - image: cibuilds/docker:18.06.3-ce

commands:
  v_build:
    parameters:
      nv:
        type: string
      islatest:
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
      - run: ./circle/docker_build << parameters.nv >> << parameters.islatest >>
      - run: ./circle/gen_testing_dockerfile << parameters.nv >>
      - run: ./circle/docker_test << parameters.nv >>
      - deploy:
          command: docker push $CONTAINER_NAME

jobs:
  build_default:
    executor: dockexec
    steps:
      - v_build:
          nv: "2.7"

  build_v3:
    executor: dockexec
    steps:
      - v_build:
          nv: "3.6"
  
  build_v3_8:
    executor: dockexec
    steps:
      - v_build:
          nv: "3.8"


  trigger-builds:
    executor: dockexec
    steps:
      - checkout
      - run: /circle/trigger_build

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build_default:
          context: org-global
      - build_v3:
          context: org-global
      - build_v3_8:
          context: org-global
      - trigger-builds:
          context: org-global
          requires:
            - build_default
            - build_v3
            - build_v3_8
          filters:
            branches:
              only:
                - master
                - release-1
