#!/bin/bash
set -eu

NV=3.10.2
imageName=$NV-testing
# ubuntu version
# sudo groupadd -g 7438 sandbox
# alpine version
# addgroup -g 7438 sandbox

# ubuntu version
# sudo adduser --system --no-create-home --shell /bin/false -u 7438 -gid 7438 sandbox
# alpine version
# adduser -S -H -s /bin/false -u 7438 -g sandbox -G sandbox sandbox
# chown -R sandbox:sandbox ${PWD}

echo "Building testing image: $imageName"
docker build -t $imageName -f Dockerfile.testing .

echo "Testing Python v$NV sandbox"
docker run $imageName -c "print(u'bats\u00E0')"
docker run -u 7438:7438 $imageName /usr/bin/redsift/protocol_test.py

INIT=$(docker inspect -f "{{index .Config.Labels \"io.redsift.sandbox.install\" }}" $imageName)
echo "Calling init = $INIT"
docker run -u 7438:7438 $imageName $INIT 0

RUN=$(docker inspect -f "{{index .Config.Labels \"io.redsift.sandbox.run\" }}" $imageName)
echo "Calling run = $RUN"
docker run -u 7438:7438 -e DRY=true $imageName $RUN 0
