#!/bin/bash
set -eu

NV=$1
CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
REVISION="-r1"
if [ $tagName == "release" ]; then
  SUFFIX=""
fi

minorv=$(echo $NV | sed "s/\([0-9]\).\([0-9]+\).*/\1.\2/")
imageName=$CONTAINER_NAME:v$minorv$REVISION$SUFFIX

cat << EOF > ./Dockerfile.testing
FROM ${imageName}
LABEL author="Christos Vontas"
LABEL email="christos@redsift.io"
LABEL version="1.0.1"

COPY --chown=7438:7438 test /run/sandbox/sift
EOF

